In [ ]:
# Code to download file into Colaboratory:
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials
# Authenticate and create the PyDrive client.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

# Breast data -----------------------
#miRNAseq
id = "1vm20ztM8XgefR1kfZiwld1fUHuVDopB_"
downloaded = drive.CreateFile({'id':id}) 
downloaded.GetContentFile('breast_miRnaSeq.csv')

#train clinical 8:2
id = "1wGYJhL2ltGg0_jGnklyTDOkuVkk9E69p"
downloaded = drive.CreateFile({'id':id}) 
downloaded.GetContentFile('train_clinical82_B.csv')

#test clinical 8:2
id = "1oU9ZSvWz_Xamc_EKDfHCNEbsI1wrh2wY"
downloaded = drive.CreateFile({'id':id}) 
downloaded.GetContentFile('test_clinical82_B.csv')

#train clinical 7:3
id = "10-4o-p0uSQl8qc8a23wU0Ibw2ul0MVJh"
downloaded = drive.CreateFile({'id':id}) 
downloaded.GetContentFile('train_clinical73_B.csv')

#test clinical 7:3
id = "1QnUOPgm3pKgr26ZntdNb_uuoc_6P2Uxy"
downloaded = drive.CreateFile({'id':id}) 
downloaded.GetContentFile('test_clinical73_B.csv')

# Glioma data ---------------------------------
#miRNAseq
id = "1zfyAT1EIo6VXI5ZGEmt2-DZHHZGN2J9M"
downloaded = drive.CreateFile({'id':id}) 
downloaded.GetContentFile('glioma_miRnaSeq.csv')

#train clinical 8:2
id = "1pXxRr81rk9lGVHY41Eovw05g11Y-00fD"
downloaded = drive.CreateFile({'id':id}) 
downloaded.GetContentFile('train_clinical82_G.csv')

#test clinical 8:2
id = "1oONCRsD38fmUM-Z9sxsFeLFAoKIprKkT"
downloaded = drive.CreateFile({'id':id}) 
downloaded.GetContentFile('test_clinical82_G.csv')

#train clinical 7:3
id = "1vOx2bB3d0Psj2XmAETJzNTSAxu9HCyNi"
downloaded = drive.CreateFile({'id':id}) 
downloaded.GetContentFile('train_clinical73_G.csv')

#test clinical 7:3
id = "1JMbn7PP4YHC-PzrrqDhzPJRmtvrtzPUO"
downloaded = drive.CreateFile({'id':id}) 
downloaded.GetContentFile('test_clinical73_G.csv')

In [ ]:
import pandas as pd
import numpy as np
import tensorflow as ts
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.autograd as autograd
import torch.optim as optim
import nltk
import sklearn
import random
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import normalize
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold


## MiRNA Cross Validation Models


In [ ]:
# build up ae model for mirna
class autoencoder(nn.Module):
  def __init__(self):
    super(autoencoder, self).__init__()
    self.encoder = nn.Sequential(
      nn.Linear(embed_dim, 256),
      nn.ReLU(True),
      nn.Linear(256, 128))
    self.decoder = nn.Sequential(
      nn.Linear(128, 256),
      nn.ReLU(True), 
      nn.Linear(256, embed_dim), 
      nn.Tanh())
    
  def forward(self, x):
      x = self.encoder(x)
      x = self.decoder(x)
      return x

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
torch.manual_seed(123)

#train_torch = torch.FloatTensor(train_scaled)
#test_torch = torch.FloatTensor(test_scaled)

criterion = nn.MSELoss()
#optimizer = optim.Adam(model.parameters(), lr=0.001)

k = 10
batch_size = 128
epochs = 10
lr = 0.001

kfold = KFold(n_splits=10, random_state=123, shuffle=True)


In [ ]:
#define train function and validation function
def train_epoch(model, device, optimizer, loss_func, dataloader):
  model.train()
  train_loss = 0.0

  for features in dataloader:

    features = features.to(device)
    optimizer.zero_grad()
    output = model(features)
    loss = loss_func(output, features)
    
    loss.backward()
    optimizer.step()

    train_loss += loss.item()

  train_loss = train_loss/len(dataloader)

  return train_loss
  
def validation_epoch(model, device, loss_func, dataloader):
  model.eval()
  valid_loss = 0.0

  for features in dataloader:
    features = features.to(device)
    output = model(features)
    loss = loss_func(output, features)

    valid_loss += loss.item()
  
  valid_loss = valid_loss/len(dataloader)

  return valid_loss

## Load Breast data


In [ ]:
breast_miRnaSeq = pd.read_csv('breast_miRnaSeq.csv')

In [ ]:
breast_miRnaSeq = breast_miRnaSeq.rename(columns={"Unnamed: 0": "attrib_name"})
breast_miRnaSeq

attrib_name  hsa-let-7a-1  ...  hsa-mir-99a  hsa-mir-99b
0    TCGA.3C.AAAU       13.1299  ...       7.0356      15.5065
1    TCGA.3C.AALI       12.9183  ...       7.8914      13.6263
2    TCGA.3C.AALJ       13.0122  ...       7.5882      15.0139
3    TCGA.3C.AALK       13.1449  ...      10.0330      14.5548
4    TCGA.4H.AAAK       13.4118  ...      10.0795      14.6504
..            ...           ...  ...          ...          ...
611  TCGA.WT.AB44       13.3759  ...      10.1058      13.9961
612  TCGA.XX.A899       14.0362  ...      10.9073      13.7815
613  TCGA.XX.A89A       13.6797  ...      10.3566      14.0595
614  TCGA.Z7.A8R5       12.9623  ...      10.1318      14.1906
615  TCGA.Z7.A8R6       13.3498  ...       8.8803      15.0567

[616 rows x 824 columns]

In [ ]:

#train test split 8:2
train_clinical82_B = pd.read_csv('train_clinical82_B.csv')
test_clinical82_B = pd.read_csv('test_clinical82_B.csv')
#train test split 7:3
train_clinical73_B = pd.read_csv('train_clinical73_B.csv')
test_clinical73_B = pd.read_csv('test_clinical73_B.csv')


In [ ]:
train_idx_82 = train_clinical82_B[['attrib_name']]
test_idx_82 = test_clinical82_B[['attrib_name']]

train_idx_73 = train_clinical73_B[['attrib_name']]
test_idx_73 = test_clinical73_B[['attrib_name']]

In [ ]:
print(train_clinical82_B.shape)
print(test_clinical82_B.shape)

print(train_clinical73_B.shape)
print(test_clinical73_B.shape)

print(train_idx_82)

(492, 22)
(124, 22)
(431, 22)
(185, 22)
      attrib_name
0    TCGA.OK.A5Q2
1    TCGA.OL.A5D7
2    TCGA.BH.A8G0
3    TCGA.D8.A1JP
4    TCGA.E9.A24A
..            ...
487  TCGA.AC.A2QI
488  TCGA.D8.A1XC
489  TCGA.E2.A1IJ
490  TCGA.E2.A14U
491  TCGA.EW.A6SC

[492 rows x 1 columns]


In [ ]:
train_clinical82_B

### Clinical 8:2


In [ ]:
print(breast_miRnaSeq.shape)

train_breast_82B = breast_miRnaSeq.merge(train_idx_82, on='attrib_name', how="inner")
test_breast_82B = breast_miRnaSeq.merge(test_idx_82, on='attrib_name', how="inner")

print(train_breast_82B.shape)
print(test_breast_82B.shape)

(616, 824)
(492, 824)
(124, 824)


In [ ]:
train_breast_82 = train_breast_82B.iloc[:, 1:]
test_breast_82 = test_breast_82B.iloc[:, 1:]
print(train_breast_82.shape)
print(test_breast_82.shape)

train_breast82_numpy = train_breast_82.to_numpy()
test_breast82_numpy = test_breast_82.to_numpy()

scaler_breast82 = MinMaxScaler()
train_breast82_scaled = scaler_breast82.fit_transform(train_breast82_numpy)
test_breast82_scaled = scaler_breast82.transform(test_breast82_numpy)



(492, 823)
(124, 823)


In [ ]:
train_breast82_torch = torch.FloatTensor(train_breast82_scaled)
test_breast82_torch = torch.FloatTensor(test_breast82_scaled)

In [ ]:
#save the attrib_name
train_breast82_name = train_breast_82B.iloc[:, 0]
test_breast82_name = test_breast_82B.iloc[:, 0]
print(train_breast82_name)
print(test_breast82_name)

train_breast82_name.to_csv("train_82B_idx.csv")
test_breast82_name.to_csv("test_82B_idx.csv")

0      TCGA.3C.AAAU
1      TCGA.3C.AALI
2      TCGA.3C.AALJ
3      TCGA.3C.AALK
4      TCGA.4H.AAAK
           ...     
487    TCGA.WT.AB41
488    TCGA.XX.A899
489    TCGA.XX.A89A
490    TCGA.Z7.A8R5
491    TCGA.Z7.A8R6
Name: attrib_name, Length: 492, dtype: object
0      TCGA.5L.AAT0
1      TCGA.A1.A0SF
2      TCGA.A1.A0SI
3      TCGA.A1.A0SQ
4      TCGA.A2.A25E
           ...     
119    TCGA.PL.A8LX
120    TCGA.S3.AA12
121    TCGA.S3.AA17
122    TCGA.W8.A86G
123    TCGA.WT.AB44
Name: attrib_name, Length: 124, dtype: object


#### breast 8:2 training and output


In [ ]:
# 10 fold cross validation
train_fold_loss = []
valid_fold_loss = []
embed_dim = train_breast82_torch.shape[1]

# assign train_torch and test_torch
train_torch = train_breast82_torch
test_torch = test_breast82_torch

for k, (train_idx,valid_idx) in enumerate(kfold.split(np.arange(len(train_torch)))):
  
  print('Fold: ', k+1 )
  train_sampler = torch.utils.data.SubsetRandomSampler(train_idx)
  valid_sampler = torch.utils.data.SubsetRandomSampler(valid_idx)

  train_loader = torch.utils.data.DataLoader(
      train_torch, batch_size=batch_size, sampler=train_sampler
  )
  valid_loader = torch.utils.data.DataLoader(
      train_torch, batch_size=batch_size, sampler=valid_sampler
  )

  model = autoencoder().to(device)
  optimizer = optim.Adam(model.parameters(), lr=lr)

  for epoch in range(epochs):
    train_loss = train_epoch(model, device, optimizer, criterion, train_loader)
    valid_loss = validation_epoch(model, device, criterion, valid_loader)

    print('epoch [{}/{}], train_loss:{:.4f}, valid_loss:{:.4f}'
          .format(epoch + 1, epochs, train_loss, valid_loss))
    
  train_fold_loss.append(train_loss)
  valid_fold_loss.append(valid_loss)

Fold:  1
epoch [1/10], train_loss:0.0880, valid_loss:0.0519
epoch [2/10], train_loss:0.0401, valid_loss:0.0254
epoch [3/10], train_loss:0.0238, valid_loss:0.0223
epoch [4/10], train_loss:0.0214, valid_loss:0.0205
epoch [5/10], train_loss:0.0199, valid_loss:0.0196
epoch [6/10], train_loss:0.0192, valid_loss:0.0189
epoch [7/10], train_loss:0.0190, valid_loss:0.0187
epoch [8/10], train_loss:0.0188, valid_loss:0.0185
epoch [9/10], train_loss:0.0183, valid_loss:0.0182
epoch [10/10], train_loss:0.0181, valid_loss:0.0181
Fold:  2
epoch [1/10], train_loss:0.0903, valid_loss:0.0576
epoch [2/10], train_loss:0.0445, valid_loss:0.0264
epoch [3/10], train_loss:0.0247, valid_loss:0.0225
epoch [4/10], train_loss:0.0218, valid_loss:0.0205
epoch [5/10], train_loss:0.0204, valid_loss:0.0193
epoch [6/10], train_loss:0.0197, valid_loss:0.0186
epoch [7/10], train_loss:0.0188, valid_loss:0.0183
epoch [8/10], train_loss:0.0190, valid_loss:0.0181
epoch [9/10], train_loss:0.0184, valid_loss:0.0180
epoch [10/10

In [ ]:
# 10 fold cv diagram

In [ ]:
# formal training
train_breast82_loader = torch.utils.data.DataLoader(
      train_breast82_torch, batch_size=batch_size, shuffle=True
  )
test_breast82_loader = torch.utils.data.DataLoader(
      test_breast82_torch, batch_size=batch_size, shuffle=False
  )

model_mirna_82B = autoencoder().to(device)
optimizer = optim.Adam(model_mirna_82B.parameters(), lr=lr)

for epoch in range(epochs):
  train_loss = train_epoch(model_mirna_82B, device, optimizer, criterion, train_breast82_loader)

  print('epoch [{}/{}], train_loss:{:.4f}'
        .format(epoch + 1, epochs, train_loss))

epoch [1/10], train_loss:0.0921
epoch [2/10], train_loss:0.0467
epoch [3/10], train_loss:0.0250
epoch [4/10], train_loss:0.0217
epoch [5/10], train_loss:0.0203
epoch [6/10], train_loss:0.0193
epoch [7/10], train_loss:0.0187
epoch [8/10], train_loss:0.0184
epoch [9/10], train_loss:0.0183
epoch [10/10], train_loss:0.0181


In [ ]:
# save and load the model
torch.save(model_mirna_82B, "mirna_82B.pt")

mirna_82B = torch.load("mirna_82B.pt")
mirna_82B

autoencoder(
  (encoder): Sequential(
    (0): Linear(in_features=823, out_features=256, bias=True)
    (1): ReLU(inplace=True)
    (2): Linear(in_features=256, out_features=128, bias=True)
  )
  (decoder): Sequential(
    (0): Linear(in_features=128, out_features=256, bias=True)
    (1): ReLU(inplace=True)
    (2): Linear(in_features=256, out_features=823, bias=True)
    (3): Tanh()
  )
)

In [ ]:
# for train data only
mirna_Tr82B_output = mirna_82B.encoder(train_breast82_torch)
print(mirna_Tr82B_output.shape)
print(mirna_Tr82B_output)
mirna_Tr82B_output = mirna_Tr82B_output.cpu().detach().numpy()
np.savetxt('mirna_Tr82B.csv', mirna_Tr82B_output, delimiter=',')

torch.Size([492, 128])
tensor([[ 0.3472,  0.4769, -0.2888,  ...,  0.2508,  0.1444, -0.2590],
        [ 0.3043,  0.4275, -0.2337,  ...,  0.1890,  0.0641, -0.1972],
        [ 0.3762,  0.4149, -0.2359,  ...,  0.2076,  0.0911, -0.2133],
        ...,
        [ 0.3559,  0.5109, -0.1798,  ...,  0.2235,  0.0059, -0.2773],
        [ 0.3541,  0.4998, -0.1805,  ...,  0.2362,  0.0288, -0.2305],
        [ 0.3908,  0.5351, -0.3024,  ...,  0.2864,  0.0809, -0.2441]],
       grad_fn=<AddmmBackward>)


In [ ]:
# for test data only

# import the saved model
id = "1BCbuKxU6PZnJIYAvaTLZkQ6ft4nASqzM"
downloaded = drive.CreateFile({'id':id}) 
downloaded.GetContentFile('mirna_82B.pt')

mirna82B = torch.load("mirna_82B.pt")
mirna82B

In [ ]:
# for test data only
mirna_Te82B_output = mirna82B.encoder(test_breast82_torch)
print(mirna_Te82B_output.shape)
print(mirna_Te82B_output)
mirna_Te82B_output = mirna_Te82B_output.cpu().detach().numpy()
np.savetxt('mirna_Test82B.csv', mirna_Te82B_output, delimiter=',')

torch.Size([124, 128])
tensor([[ 0.3236,  0.4208, -0.1996,  ...,  0.1882,  0.0578, -0.1825],
        [ 0.3562,  0.4930, -0.1992,  ...,  0.2296,  0.0623, -0.2392],
        [ 0.3755,  0.4748, -0.1927,  ...,  0.2099,  0.0559, -0.2157],
        ...,
        [ 0.3190,  0.4189, -0.2511,  ...,  0.2483,  0.0667, -0.1870],
        [ 0.3443,  0.5037, -0.2049,  ...,  0.2250, -0.0167, -0.2245],
        [ 0.3424,  0.4770, -0.2056,  ...,  0.2137,  0.0218, -0.2275]],
       grad_fn=<AddmmBackward>)


In [ ]:
# for whole data only

### Clinical 7:3


In [ ]:
train_breast_73B = breast_miRnaSeq.merge(train_idx_73, how="inner")
test_breast_73B = breast_miRnaSeq.merge(test_idx_73, how="inner")

In [ ]:
print(train_breast_73B.shape)
print(test_breast_73B.shape)
print(train_breast_73B)
print(test_breast_73B)

(431, 824)
(185, 824)
      attrib_name  hsa-let-7a-1  ...  hsa-mir-99a  hsa-mir-99b
0    TCGA.3C.AAAU       13.1299  ...       7.0356      15.5065
1    TCGA.3C.AALI       12.9183  ...       7.8914      13.6263
2    TCGA.3C.AALJ       13.0122  ...       7.5882      15.0139
3    TCGA.3C.AALK       13.1449  ...      10.0330      14.5548
4    TCGA.4H.AAAK       13.4118  ...      10.0795      14.6504
..            ...           ...  ...          ...          ...
426  TCGA.WT.AB41       13.0353  ...       9.7652      14.4590
427  TCGA.XX.A899       14.0362  ...      10.9073      13.7815
428  TCGA.XX.A89A       13.6797  ...      10.3566      14.0595
429  TCGA.Z7.A8R5       12.9623  ...      10.1318      14.1906
430  TCGA.Z7.A8R6       13.3498  ...       8.8803      15.0567

[431 rows x 824 columns]
      attrib_name  hsa-let-7a-1  ...  hsa-mir-99a  hsa-mir-99b
0    TCGA.5L.AAT0       13.3164  ...       9.3659      14.1468
1    TCGA.A1.A0SF       12.3430  ...      10.9691      15.2262
2    TC

In [ ]:
train_breast_73 = train_breast_73B.iloc[:, 1:]
test_breast_73 = test_breast_73B.iloc[:, 1:]
print(test_breast_73.shape)
print(train_breast_73.shape)
train_breast73_numpy = train_breast_73.to_numpy()
test_breast73_numpy = test_breast_73.to_numpy()

scaler_breast73 = MinMaxScaler()

train_breast73_scaled = scaler_breast73.fit_transform(train_breast73_numpy)
test_breast73_scaled = scaler_breast73.transform(test_breast73_numpy)

(185, 823)
(431, 823)


In [ ]:
train_breast73_torch = torch.FloatTensor(train_breast73_scaled)
test_breast73_torch = torch.FloatTensor(test_breast73_scaled)

In [ ]:
#save the attrib_name
train_breast73_name = train_breast_73B.iloc[:, 0]
test_breast73_name = test_breast_73B.iloc[:, 0]
print(train_breast73_name)
print(test_breast73_name)

train_breast73_name.to_csv("train_73B_idx.csv")
test_breast73_name.to_csv("test_73B_idx.csv")

0      TCGA.3C.AAAU
1      TCGA.3C.AALI
2      TCGA.3C.AALJ
3      TCGA.3C.AALK
4      TCGA.4H.AAAK
           ...     
426    TCGA.WT.AB41
427    TCGA.XX.A899
428    TCGA.XX.A89A
429    TCGA.Z7.A8R5
430    TCGA.Z7.A8R6
Name: attrib_name, Length: 431, dtype: object
0      TCGA.5L.AAT0
1      TCGA.A1.A0SF
2      TCGA.A1.A0SI
3      TCGA.A1.A0SQ
4      TCGA.A2.A0CO
           ...     
180    TCGA.S3.AA12
181    TCGA.S3.AA17
182    TCGA.UL.AAZ6
183    TCGA.W8.A86G
184    TCGA.WT.AB44
Name: attrib_name, Length: 185, dtype: object


#### breast 7:3 training and output


In [ ]:
# 10 fold cross validation
train_fold_loss = []
valid_fold_loss = []
embed_dim = train_breast73_torch.shape[1]

# assign train_torch and test_torch
train_torch = train_breast73_torch
test_torch = tesr_breast73_torch

for k, (train_idx,valid_idx) in enumerate(kfold.split(np.arange(len(train_torch)))):
  
  print('Fold: ', k+1 )
  train_sampler = torch.utils.data.SubsetRandomSampler(train_idx)
  valid_sampler = torch.utils.data.SubsetRandomSampler(valid_idx)

  train_loader = torch.utils.data.DataLoader(
      train_torch, batch_size=batch_size, sampler=train_sampler
  )
  valid_loader = torch.utils.data.DataLoader(
      train_torch, batch_size=batch_size, sampler=valid_sampler
  )

  model = autoencoder().to(device)
  optimizer = optim.Adam(model.parameters(), lr=lr)

  for epoch in range(epochs):
    train_loss = train_epoch(model, device, optimizer, criterion, train_loader)
    valid_loss = validation_epoch(model, device, criterion, valid_loader)

    print('epoch [{}/{}], train_loss:{:.4f}, valid_loss:{:.4f}'
          .format(epoch + 1, epochs, train_loss, valid_loss))
    
  train_fold_loss.append(train_loss)
  valid_fold_loss.append(valid_loss)

Fold:  1
epoch [1/10], train_loss:0.0920, valid_loss:0.0624
epoch [2/10], train_loss:0.0472, valid_loss:0.0279
epoch [3/10], train_loss:0.0254, valid_loss:0.0227
epoch [4/10], train_loss:0.0218, valid_loss:0.0215
epoch [5/10], train_loss:0.0211, valid_loss:0.0202
epoch [6/10], train_loss:0.0193, valid_loss:0.0193
epoch [7/10], train_loss:0.0198, valid_loss:0.0189
epoch [8/10], train_loss:0.0205, valid_loss:0.0189
epoch [9/10], train_loss:0.0192, valid_loss:0.0188
epoch [10/10], train_loss:0.0187, valid_loss:0.0186
Fold:  2
epoch [1/10], train_loss:0.0931, valid_loss:0.0698
epoch [2/10], train_loss:0.0515, valid_loss:0.0345
epoch [3/10], train_loss:0.0278, valid_loss:0.0257
epoch [4/10], train_loss:0.0237, valid_loss:0.0242
epoch [5/10], train_loss:0.0208, valid_loss:0.0232
epoch [6/10], train_loss:0.0210, valid_loss:0.0224
epoch [7/10], train_loss:0.0199, valid_loss:0.0219
epoch [8/10], train_loss:0.0189, valid_loss:0.0217
epoch [9/10], train_loss:0.0208, valid_loss:0.0215
epoch [10/10

In [ ]:
# 10 fold cv diagram

In [ ]:
# formal training
train_breast73_loader = torch.utils.data.DataLoader(
      train_breast73_torch, batch_size=batch_size, shuffle=True
  )
test_breast73_loader = torch.utils.data.DataLoader(
      test_breast73_torch, batch_size=batch_size, shuffle=False
  )

model_mirna_73B = autoencoder().to(device)
optimizer = optim.Adam(model_mirna_73B.parameters(), lr=lr)

for epoch in range(epochs):
  train_loss = train_epoch(model_mirna_73B, device, optimizer, criterion, train_breast73_loader)

  print('epoch [{}/{}], train_loss:{:.4f}'
        .format(epoch + 1, epochs, train_loss))

epoch [1/10], train_loss:0.0943
epoch [2/10], train_loss:0.0478
epoch [3/10], train_loss:0.0248
epoch [4/10], train_loss:0.0231
epoch [5/10], train_loss:0.0217
epoch [6/10], train_loss:0.0203
epoch [7/10], train_loss:0.0200
epoch [8/10], train_loss:0.0196
epoch [9/10], train_loss:0.0193
epoch [10/10], train_loss:0.0189


In [ ]:
# save and load the model
torch.save(model_mirna_73B, "mirna_73B.pt")

mirna_73B = torch.load("mirna_73B.pt")
mirna_73B

autoencoder(
  (encoder): Sequential(
    (0): Linear(in_features=823, out_features=256, bias=True)
    (1): ReLU(inplace=True)
    (2): Linear(in_features=256, out_features=128, bias=True)
  )
  (decoder): Sequential(
    (0): Linear(in_features=128, out_features=256, bias=True)
    (1): ReLU(inplace=True)
    (2): Linear(in_features=256, out_features=823, bias=True)
    (3): Tanh()
  )
)

In [ ]:
# for train data only
mirna_Tr73B_output = mirna_73B.encoder(train_breast73_torch)
print(mirna_Tr73B_output.shape)
print(mirna_Tr73B_output)
mirna_Tr73B_output = mirna_Tr73B_output.cpu().detach().numpy()
np.savetxt('mirna_Tr73B.csv', mirna_Tr73B_output, delimiter=',')

torch.Size([431, 128])
tensor([[ 0.1343, -0.0950,  1.1333,  ...,  0.3808, -0.4243, -0.0919],
        [ 0.0964, -0.1436,  0.9825,  ...,  0.3630, -0.3531, -0.0932],
        [ 0.0906, -0.1018,  0.9736,  ...,  0.3337, -0.3592, -0.0661],
        ...,
        [ 0.0415, -0.1380,  1.0221,  ...,  0.2895, -0.3268, -0.1182],
        [ 0.0351, -0.1305,  1.0161,  ...,  0.3120, -0.3237, -0.0681],
        [ 0.1511, -0.1229,  1.1963,  ...,  0.3657, -0.4316, -0.1181]],
       grad_fn=<AddmmBackward>)


In [ ]:
# for test data only

# import the saved model
id = "115q9iJnkCdyRslzblv-Er7F5fe5XfoRA"
downloaded = drive.CreateFile({'id':id}) 
downloaded.GetContentFile('mirna_73B.pt')

mirna73B = torch.load("mirna_73B.pt")
mirna73B

autoencoder(
  (encoder): Sequential(
    (0): Linear(in_features=823, out_features=256, bias=True)
    (1): ReLU(inplace=True)
    (2): Linear(in_features=256, out_features=128, bias=True)
  )
  (decoder): Sequential(
    (0): Linear(in_features=128, out_features=256, bias=True)
    (1): ReLU(inplace=True)
    (2): Linear(in_features=256, out_features=823, bias=True)
    (3): Tanh()
  )
)

In [ ]:
# for test data only
mirna_Te73B_output = mirna73B.encoder(test_breast73_torch)
print(mirna_Te73B_output.shape)
print(mirna_Te73B_output)
mirna_Te73B_output = mirna_Te73B_output.cpu().detach().numpy()
np.savetxt('mirna_Test73B.csv', mirna_Te73B_output, delimiter=',')

torch.Size([185, 128])
tensor([[ 0.0499, -0.1045,  0.8669,  ...,  0.2767, -0.2627, -0.1152],
        [ 0.0701, -0.1339,  1.0166,  ...,  0.3394, -0.3153, -0.0722],
        [ 0.0471, -0.1317,  0.9600,  ...,  0.3192, -0.3143, -0.0767],
        ...,
        [ 0.1442, -0.1049,  0.9218,  ...,  0.3153, -0.3226, -0.1197],
        [ 0.0334, -0.1317,  1.0058,  ...,  0.3234, -0.3164, -0.1049],
        [ 0.0356, -0.1398,  0.9379,  ...,  0.2792, -0.3173, -0.0782]],
       grad_fn=<AddmmBackward>)


In [ ]:
# for whole data only

## Load Glioma data

In [ ]:
glioma_miRnaSeq = pd.read_csv('glioma_miRnaSeq.csv')
glioma_miRnaSeq = glioma_miRnaSeq.rename(columns={"Unnamed: 0": "attrib_name"})

glioma_miRnaSeq

attrib_name  hsa-let-7a-1  ...  hsa-mir-99a  hsa-mir-99b
0    TCGA.CS.4938       12.6226  ...      13.0651      15.7755
1    TCGA.CS.4941       11.8102  ...      10.8423      14.1382
2    TCGA.CS.4942       11.1146  ...      10.1744      12.8643
3    TCGA.CS.4943       10.8885  ...       9.8865      13.0006
4    TCGA.CS.4944       11.7949  ...      11.7756      13.6348
..            ...           ...  ...          ...          ...
503  TCGA.WY.A85A       12.7427  ...      11.3999      14.5000
504  TCGA.WY.A85B       12.8910  ...      11.6821      13.8018
505  TCGA.WY.A85C       12.9008  ...      11.7779      13.5597
506  TCGA.WY.A85D       12.6632  ...      11.6534      13.9789
507  TCGA.WY.A85E       12.5092  ...      10.3715      13.6777

[508 rows x 792 columns]

In [ ]:

#train test split 8:2
train_clinical82_G = pd.read_csv('train_clinical82_G.csv')
train_clinical82_G = train_clinical82_G.rename(columns={"Unnamed: 0.1": "attrib_name"})

test_clinical82_G = pd.read_csv('test_clinical82_G.csv')
test_clinical82_G = test_clinical82_G.rename(columns={"Unnamed: 0.1": "attrib_name"})

print(train_clinical82_G.shape)
print(test_clinical82_G.shape)
#train test split 7:3
train_clinical73_G = pd.read_csv('train_clinical73_G.csv')
train_clinical73_G = train_clinical73_G.rename(columns={"Unnamed: 0.1": "attrib_name"})

test_clinical73_G = pd.read_csv('test_clinical73_G.csv')
test_clinical73_G = test_clinical73_G.rename(columns={"Unnamed: 0.1": "attrib_name"})

print(train_clinical73_G.shape)
print(test_clinical73_G.shape)

(406, 11)
(102, 11)
(355, 11)
(153, 11)


In [ ]:
train_clinical82_G

Unnamed: 0   attrib_name  ...  status overallsurvival
0           151  TCGA.DU.A7TI  ...     1.0          1183,1
1           347  TCGA.P5.A5EU  ...     NaN           NA,NA
2           469  TCGA.TM.A84T  ...     0.0           724,0
3           442  TCGA.S9.A7QZ  ...     0.0           826,0
4           292  TCGA.HT.8015  ...     NaN           NA,NA
..          ...           ...  ...     ...             ...
401          98  TCGA.DU.7007  ...     1.0          1915,1
402         476  TCGA.TQ.A7RM  ...     0.0          1116,0
403         322  TCGA.HT.A61C  ...     1.0           537,1
404         382  TCGA.QH.A6CZ  ...     0.0           279,0
405         365  TCGA.P5.A735  ...     0.0           292,0

[406 rows x 11 columns]

In [ ]:
train_idx_82G = train_clinical82_G[['attrib_name']]
test_idx_82G = test_clinical82_G[['attrib_name']]

train_idx_73G = train_clinical73_G[['attrib_name']]
test_idx_73G = test_clinical73_G[['attrib_name']]

In [ ]:
train_idx_82G

attrib_name
0    TCGA.DU.A7TI
1    TCGA.P5.A5EU
2    TCGA.TM.A84T
3    TCGA.S9.A7QZ
4    TCGA.HT.8015
..            ...
401  TCGA.DU.7007
402  TCGA.TQ.A7RM
403  TCGA.HT.A61C
404  TCGA.QH.A6CZ
405  TCGA.P5.A735

[406 rows x 1 columns]

### Clinical 8:2

In [ ]:
print(glioma_miRnaSeq.shape)

train_glioma_82G = glioma_miRnaSeq.merge(train_idx_82G, on='attrib_name', how="inner")
test_glioma_82G = glioma_miRnaSeq.merge(test_idx_82G, on='attrib_name', how="inner")

print(train_glioma_82G.shape)
print(test_glioma_82G.shape)

(508, 792)
(406, 792)
(102, 792)


In [ ]:
train_glioma_82G

attrib_name  hsa-let-7a-1  ...  hsa-mir-99a  hsa-mir-99b
0    TCGA.CS.4938       12.6226  ...      13.0651      15.7755
1    TCGA.CS.4941       11.8102  ...      10.8423      14.1382
2    TCGA.CS.4942       11.1146  ...      10.1744      12.8643
3    TCGA.CS.4943       10.8885  ...       9.8865      13.0006
4    TCGA.CS.4944       11.7949  ...      11.7756      13.6348
..            ...           ...  ...          ...          ...
401  TCGA.WY.A858       12.4502  ...      11.8029      14.1280
402  TCGA.WY.A85A       12.7427  ...      11.3999      14.5000
403  TCGA.WY.A85B       12.8910  ...      11.6821      13.8018
404  TCGA.WY.A85C       12.9008  ...      11.7779      13.5597
405  TCGA.WY.A85E       12.5092  ...      10.3715      13.6777

[406 rows x 792 columns]

In [ ]:
train_glioma_82 = train_glioma_82G.iloc[:, 1:]
test_glioma_82 = test_glioma_82G.iloc[:, 1:]
print(train_glioma_82.shape)
print(test_glioma_82.shape)

train_glioma82_numpy = train_glioma_82.to_numpy()
test_glioma82_numpy = test_glioma_82.to_numpy()

scaler_glioma82 = MinMaxScaler()
train_glioma82_scaled = scaler_glioma82.fit_transform(train_glioma82_numpy)
test_glioma82_scaled = scaler_glioma82.transform(test_glioma82_numpy)

(406, 791)
(102, 791)


In [ ]:
train_glioma82_torch = torch.FloatTensor(train_glioma82_scaled)
test_glioma82_torch = torch.FloatTensor(test_glioma82_scaled)

In [ ]:
#save the attrib_name
train_glioma82_name = train_glioma_82G.iloc[:, 0]
test_glioma82_name = test_glioma_82G.iloc[:, 0]
print(train_glioma82_name)
print(test_glioma82_name)

train_glioma82_name.to_csv("train_82G_idx.csv")
test_glioma82_name.to_csv("test_82G_idx.csv")

0      TCGA.CS.4938
1      TCGA.CS.4941
2      TCGA.CS.4942
3      TCGA.CS.4943
4      TCGA.CS.4944
           ...     
401    TCGA.WY.A858
402    TCGA.WY.A85A
403    TCGA.WY.A85B
404    TCGA.WY.A85C
405    TCGA.WY.A85E
Name: attrib_name, Length: 406, dtype: object
0      TCGA.CS.5390
1      TCGA.CS.5396
2      TCGA.CS.6186
3      TCGA.CS.6290
4      TCGA.CS.6666
           ...     
97     TCGA.VM.A8C8
98     TCGA.VV.A86M
99     TCGA.VW.A7QS
100    TCGA.WY.A859
101    TCGA.WY.A85D
Name: attrib_name, Length: 102, dtype: object


#### Glioma 8:2 training and output


In [ ]:
# 10 fold cross validation
train_fold_loss = []
valid_fold_loss = []
embed_dim = train_glioma82_torch.shape[1]

# assign train_torch and test_torch
train_torch = train_glioma82_torch
test_torch = test_glioma82_torch

for k, (train_idx,valid_idx) in enumerate(kfold.split(np.arange(len(train_torch)))):
  
  print('Fold: ', k+1 )
  train_sampler = torch.utils.data.SubsetRandomSampler(train_idx)
  valid_sampler = torch.utils.data.SubsetRandomSampler(valid_idx)

  train_loader = torch.utils.data.DataLoader(
      train_torch, batch_size=batch_size, sampler=train_sampler
  )
  valid_loader = torch.utils.data.DataLoader(
      train_torch, batch_size=batch_size, sampler=valid_sampler
  )

  model = autoencoder().to(device)
  optimizer = optim.Adam(model.parameters(), lr=lr)

  for epoch in range(epochs):
    train_loss = train_epoch(model, device, optimizer, criterion, train_loader)
    valid_loss = validation_epoch(model, device, criterion, valid_loader)

    print('epoch [{}/{}], train_loss:{:.4f}, valid_loss:{:.4f}'
          .format(epoch + 1, epochs, train_loss, valid_loss))
    
  train_fold_loss.append(train_loss)
  valid_fold_loss.append(valid_loss)

Fold:  1
epoch [1/10], train_loss:0.1059, valid_loss:0.0795
epoch [2/10], train_loss:0.0641, valid_loss:0.0437
epoch [3/10], train_loss:0.0349, valid_loss:0.0260
epoch [4/10], train_loss:0.0244, valid_loss:0.0238
epoch [5/10], train_loss:0.0229, valid_loss:0.0229
epoch [6/10], train_loss:0.0215, valid_loss:0.0220
epoch [7/10], train_loss:0.0205, valid_loss:0.0211
epoch [8/10], train_loss:0.0199, valid_loss:0.0203
epoch [9/10], train_loss:0.0194, valid_loss:0.0200
epoch [10/10], train_loss:0.0191, valid_loss:0.0198
Fold:  2
epoch [1/10], train_loss:0.1077, valid_loss:0.0891
epoch [2/10], train_loss:0.0707, valid_loss:0.0487
epoch [3/10], train_loss:0.0391, valid_loss:0.0275
epoch [4/10], train_loss:0.0254, valid_loss:0.0229
epoch [5/10], train_loss:0.0228, valid_loss:0.0221
epoch [6/10], train_loss:0.0219, valid_loss:0.0213
epoch [7/10], train_loss:0.0210, valid_loss:0.0202
epoch [8/10], train_loss:0.0201, valid_loss:0.0194
epoch [9/10], train_loss:0.0195, valid_loss:0.0190
epoch [10/10

In [ ]:
# 10 fold cv diagram

In [ ]:
# formal training
train_glioma82_loader = torch.utils.data.DataLoader(
      train_glioma82_torch, batch_size=batch_size, shuffle=True
  )
test_glioma82_loader = torch.utils.data.DataLoader(
      test_glioma82_torch, batch_size=batch_size, shuffle=False
  )

model_mirna_82G = autoencoder().to(device)
optimizer = optim.Adam(model_mirna_82G.parameters(), lr=lr)

for epoch in range(epochs):
  train_loss = train_epoch(model_mirna_82G, device, optimizer, criterion, train_glioma82_loader)

  print('epoch [{}/{}], train_loss:{:.4f}'
        .format(epoch + 1, epochs, train_loss))

epoch [1/10], train_loss:0.1032
epoch [2/10], train_loss:0.0548
epoch [3/10], train_loss:0.0279
epoch [4/10], train_loss:0.0233
epoch [5/10], train_loss:0.0217
epoch [6/10], train_loss:0.0205
epoch [7/10], train_loss:0.0199
epoch [8/10], train_loss:0.0198
epoch [9/10], train_loss:0.0190
epoch [10/10], train_loss:0.0194


In [ ]:
# save and load the model
torch.save(model_mirna_82G, "mirna_82G.pt")

mirna_82G = torch.load("mirna_82G.pt")
mirna_82G

autoencoder(
  (encoder): Sequential(
    (0): Linear(in_features=791, out_features=256, bias=True)
    (1): ReLU(inplace=True)
    (2): Linear(in_features=256, out_features=128, bias=True)
  )
  (decoder): Sequential(
    (0): Linear(in_features=128, out_features=256, bias=True)
    (1): ReLU(inplace=True)
    (2): Linear(in_features=256, out_features=791, bias=True)
    (3): Tanh()
  )
)

In [ ]:
# for train data only
mirna_Tr82G_output = mirna_82G.encoder(train_glioma82_torch)
print(mirna_Tr82G_output.shape)
print(mirna_Tr82G_output)
mirna_Tr82G_output = mirna_Tr82G_output.cpu().detach().numpy()
np.savetxt('mirna_Tr82G.csv', mirna_Tr82G_output, delimiter=',')

torch.Size([406, 128])
tensor([[ 0.0989,  0.3143, -0.0319,  ..., -0.0825,  0.0637, -0.0956],
        [ 0.0636,  0.3023,  0.0504,  ..., -0.0685,  0.0562, -0.1120],
        [ 0.0967,  0.1918,  0.0559,  ..., -0.0577,  0.0548, -0.0569],
        ...,
        [ 0.0949,  0.3331,  0.0159,  ..., -0.0750,  0.1060, -0.0914],
        [ 0.0880,  0.3310,  0.0483,  ..., -0.0937,  0.0833, -0.0489],
        [ 0.0998,  0.3365,  0.0280,  ..., -0.1167,  0.0829, -0.1249]],
       grad_fn=<AddmmBackward>)


In [ ]:
# for test data only

In [ ]:
# for test data only

# import the saved model
id = "1nKcBgQOCp4XIGL81NbAlpedMf28HUdWo"
downloaded = drive.CreateFile({'id':id}) 
downloaded.GetContentFile('mirna_82G.pt')

mirna82G = torch.load("mirna_82G.pt")
mirna82G

autoencoder(
  (encoder): Sequential(
    (0): Linear(in_features=791, out_features=256, bias=True)
    (1): ReLU(inplace=True)
    (2): Linear(in_features=256, out_features=128, bias=True)
  )
  (decoder): Sequential(
    (0): Linear(in_features=128, out_features=256, bias=True)
    (1): ReLU(inplace=True)
    (2): Linear(in_features=256, out_features=791, bias=True)
    (3): Tanh()
  )
)

In [ ]:
# for test data only
mirna_Te82G_output = mirna82G.encoder(test_glioma82_torch)
print(mirna_Te82G_output.shape)
print(mirna_Te82G_output)
mirna_Te82G_output = mirna_Te82G_output.cpu().detach().numpy()
np.savetxt('mirna_Test82G.csv', mirna_Te82G_output, delimiter=',')

torch.Size([102, 128])
tensor([[ 0.1087,  0.2322,  0.0404,  ..., -0.0566,  0.0823, -0.0778],
        [ 0.0739,  0.2292,  0.0214,  ..., -0.0410,  0.0456, -0.1059],
        [ 0.0628,  0.2563, -0.0135,  ..., -0.0645,  0.0346, -0.0548],
        ...,
        [ 0.0790,  0.1920, -0.0027,  ..., -0.1089,  0.0170, -0.0786],
        [ 0.1077,  0.4279,  0.1139,  ..., -0.0782,  0.1387, -0.1380],
        [ 0.0987,  0.2703, -0.0167,  ..., -0.1002,  0.0421, -0.1152]],
       grad_fn=<AddmmBackward>)


In [ ]:
# for whole data only

### Clinical 7:3

In [ ]:
print(glioma_miRnaSeq.shape)

train_glioma_73G = glioma_miRnaSeq.merge(train_idx_73G, on='attrib_name', how="inner")
test_glioma_73G = glioma_miRnaSeq.merge(test_idx_73G, on='attrib_name', how="inner")

print(train_glioma_73G.shape)
print(test_glioma_73G.shape)

(508, 792)
(355, 792)
(153, 792)


In [ ]:
test_glioma_73G

attrib_name  hsa-let-7a-1  ...  hsa-mir-99a  hsa-mir-99b
0    TCGA.CS.4938       12.6226  ...      13.0651      15.7755
1    TCGA.CS.5390       11.9711  ...       9.5536      12.8821
2    TCGA.CS.5396       11.9079  ...       8.9760      12.9193
3    TCGA.CS.6186       13.4597  ...      11.7450      16.8502
4    TCGA.CS.6290       13.4212  ...      11.9511      14.5708
..            ...           ...  ...          ...          ...
148  TCGA.VM.A8C9       13.9784  ...      11.8441      15.0379
149  TCGA.VV.A86M       13.3444  ...      12.7306      14.0264
150  TCGA.VW.A7QS       12.7043  ...      11.3946      12.7069
151  TCGA.WY.A859       12.2999  ...      11.2630      14.4195
152  TCGA.WY.A85D       12.6632  ...      11.6534      13.9789

[153 rows x 792 columns]

In [ ]:
train_glioma_73 = train_glioma_73G.iloc[:, 1:]
test_glioma_73 = test_glioma_73G.iloc[:, 1:]
print(train_glioma_73.shape)
print(test_glioma_73.shape)
train_glioma73_numpy = train_glioma_73.to_numpy()
test_glioma73_numpy = test_glioma_73.to_numpy()

scaler_glioma73 = MinMaxScaler()
train_glioma73_scaled = scaler_glioma73.fit_transform(train_glioma73_numpy)
test_glioma73_scaled = scaler_glioma73.transform(test_glioma73_numpy)

(355, 791)
(153, 791)


In [ ]:
train_glioma73_torch = torch.FloatTensor(train_glioma73_scaled)
test_glioma73_torch = torch.FloatTensor(test_glioma73_scaled)

In [ ]:
#save the attrib_name
train_glioma73_name = train_glioma_73G.iloc[:, 0]
test_glioma73_name = test_glioma_73G.iloc[:, 0]
print(train_glioma73_name)
print(test_glioma73_name)

train_glioma73_name.to_csv("train_73G_idx.csv")
test_glioma73_name.to_csv("test_73G_idx.csv")

0      TCGA.CS.4941
1      TCGA.CS.4942
2      TCGA.CS.4943
3      TCGA.CS.4944
4      TCGA.CS.5393
           ...     
350    TCGA.WY.A858
351    TCGA.WY.A85A
352    TCGA.WY.A85B
353    TCGA.WY.A85C
354    TCGA.WY.A85E
Name: attrib_name, Length: 355, dtype: object
0      TCGA.CS.4938
1      TCGA.CS.5390
2      TCGA.CS.5396
3      TCGA.CS.6186
4      TCGA.CS.6290
           ...     
148    TCGA.VM.A8C9
149    TCGA.VV.A86M
150    TCGA.VW.A7QS
151    TCGA.WY.A859
152    TCGA.WY.A85D
Name: attrib_name, Length: 153, dtype: object


#### Glioma 7:3 training and output


In [ ]:
# 10 fold cross validation
train_fold_loss = []
valid_fold_loss = []
embed_dim = train_glioma73_torch.shape[1]

# assign train_torch and test_torch
train_torch = train_glioma73_torch
test_torch = test_glioma73_torch

for k, (train_idx,valid_idx) in enumerate(kfold.split(np.arange(len(train_torch)))):
  
  print('Fold: ', k+1 )
  train_sampler = torch.utils.data.SubsetRandomSampler(train_idx)
  valid_sampler = torch.utils.data.SubsetRandomSampler(valid_idx)

  train_loader = torch.utils.data.DataLoader(
      train_torch, batch_size=batch_size, sampler=train_sampler
  )
  valid_loader = torch.utils.data.DataLoader(
      train_torch, batch_size=batch_size, sampler=valid_sampler
  )

  model = autoencoder().to(device)
  optimizer = optim.Adam(model.parameters(), lr=lr)

  for epoch in range(epochs):
    train_loss = train_epoch(model, device, optimizer, criterion, train_loader)
    valid_loss = validation_epoch(model, device, criterion, valid_loader)

    print('epoch [{}/{}], train_loss:{:.4f}, valid_loss:{:.4f}'
          .format(epoch + 1, epochs, train_loss, valid_loss))
    
  train_fold_loss.append(train_loss)
  valid_fold_loss.append(valid_loss)

Fold:  1
epoch [1/10], train_loss:0.1085, valid_loss:0.0973
epoch [2/10], train_loss:0.0676, valid_loss:0.0536
epoch [3/10], train_loss:0.0379, valid_loss:0.0321
epoch [4/10], train_loss:0.0255, valid_loss:0.0293
epoch [5/10], train_loss:0.0236, valid_loss:0.0283
epoch [6/10], train_loss:0.0221, valid_loss:0.0273
epoch [7/10], train_loss:0.0209, valid_loss:0.0257
epoch [8/10], train_loss:0.0205, valid_loss:0.0251
epoch [9/10], train_loss:0.0202, valid_loss:0.0247
epoch [10/10], train_loss:0.0195, valid_loss:0.0244
Fold:  2
epoch [1/10], train_loss:0.1091, valid_loss:0.0813
epoch [2/10], train_loss:0.0654, valid_loss:0.0461
epoch [3/10], train_loss:0.0361, valid_loss:0.0276
epoch [4/10], train_loss:0.0255, valid_loss:0.0258
epoch [5/10], train_loss:0.0239, valid_loss:0.0252
epoch [6/10], train_loss:0.0224, valid_loss:0.0238
epoch [7/10], train_loss:0.0219, valid_loss:0.0228
epoch [8/10], train_loss:0.0208, valid_loss:0.0221
epoch [9/10], train_loss:0.0207, valid_loss:0.0218
epoch [10/10

In [ ]:
# 10 fold cv diagram

In [ ]:
# formal training
train_glioma73_loader = torch.utils.data.DataLoader(
      train_glioma73_torch, batch_size=batch_size, shuffle=True
  )
test_glioma73_loader = torch.utils.data.DataLoader(
      test_glioma73_torch, batch_size=batch_size, shuffle=False
  )

model_mirna_73G = autoencoder().to(device)
optimizer = optim.Adam(model_mirna_73G.parameters(), lr=lr)

for epoch in range(epochs):
  train_loss = train_epoch(model_mirna_73G, device, optimizer, criterion, train_glioma73_loader)

  print('epoch [{}/{}], train_loss:{:.4f}'
        .format(epoch + 1, epochs, train_loss))

epoch [1/10], train_loss:0.1094
epoch [2/10], train_loss:0.0707
epoch [3/10], train_loss:0.0382
epoch [4/10], train_loss:0.0259
epoch [5/10], train_loss:0.0240
epoch [6/10], train_loss:0.0225
epoch [7/10], train_loss:0.0218
epoch [8/10], train_loss:0.0209
epoch [9/10], train_loss:0.0202
epoch [10/10], train_loss:0.0200


In [ ]:
# save and load the model
torch.save(model_mirna_73G, "mirna_73G.pt")

mirna_73G = torch.load("mirna_73G.pt")
mirna_73G

autoencoder(
  (encoder): Sequential(
    (0): Linear(in_features=791, out_features=256, bias=True)
    (1): ReLU(inplace=True)
    (2): Linear(in_features=256, out_features=128, bias=True)
  )
  (decoder): Sequential(
    (0): Linear(in_features=128, out_features=256, bias=True)
    (1): ReLU(inplace=True)
    (2): Linear(in_features=256, out_features=791, bias=True)
    (3): Tanh()
  )
)

In [ ]:
# for train data only
mirna_Tr73G_output = mirna_73G.encoder(train_glioma73_torch)
print(mirna_Tr73G_output.shape)
print(mirna_Tr73G_output)
mirna_Tr73G_output = mirna_Tr73G_output.cpu().detach().numpy()
np.savetxt('mirna_Tr73G.csv', mirna_Tr73G_output, delimiter=',')

torch.Size([355, 128])
tensor([[ 6.4726e-02, -4.2632e-01, -3.5382e-01,  ..., -1.2889e-02,
          7.1031e-02, -1.0436e+00],
        [-9.2673e-03, -2.1383e-01, -2.4442e-01,  ..., -3.5325e-02,
          2.2565e-02, -6.8443e-01],
        [ 2.5302e-03, -2.6197e-01, -2.4555e-01,  ..., -1.5348e-02,
          7.6830e-02, -7.4028e-01],
        ...,
        [ 4.5974e-02, -3.4195e-01, -3.6260e-01,  ...,  1.1801e-02,
          8.5198e-02, -1.0136e+00],
        [ 3.7366e-02, -4.3328e-01, -4.0167e-01,  ...,  3.9748e-02,
          6.0322e-02, -1.0789e+00],
        [ 2.2317e-04, -3.4477e-01, -3.6741e-01,  ...,  6.3414e-02,
         -6.3524e-02, -9.5566e-01]], grad_fn=<AddmmBackward>)


In [ ]:
# for test data only

# import the saved model
id = "1HfRnDTMEhfmRokSNRdnvSZQhDtVws4KX"
downloaded = drive.CreateFile({'id':id}) 
downloaded.GetContentFile('mirna_73G.pt')

mirna73G = torch.load("mirna_73G.pt")
mirna73G

autoencoder(
  (encoder): Sequential(
    (0): Linear(in_features=791, out_features=256, bias=True)
    (1): ReLU(inplace=True)
    (2): Linear(in_features=256, out_features=128, bias=True)
  )
  (decoder): Sequential(
    (0): Linear(in_features=128, out_features=256, bias=True)
    (1): ReLU(inplace=True)
    (2): Linear(in_features=256, out_features=791, bias=True)
    (3): Tanh()
  )
)

In [ ]:
# for test data only
mirna_Te73G_output = mirna73G.encoder(test_glioma73_torch)
print(mirna_Te73G_output.shape)
print(mirna_Te73G_output)
mirna_Te73G_output = mirna_Te73G_output.cpu().detach().numpy()
np.savetxt('mirna_Test73G.csv', mirna_Te73G_output, delimiter=',')

torch.Size([153, 128])
tensor([[ 0.0949, -0.3832, -0.3728,  ...,  0.0486,  0.0377, -1.0439],
        [ 0.0031, -0.2848, -0.2804,  ..., -0.0015,  0.0326, -0.7668],
        [ 0.0182, -0.2588, -0.2258,  ..., -0.0125,  0.0437, -0.7629],
        ...,
        [ 0.0066, -0.2992, -0.2122,  ..., -0.0280,  0.0579, -0.7181],
        [ 0.0751, -0.4864, -0.5458,  ..., -0.0046,  0.0725, -1.4314],
        [ 0.0399, -0.3030, -0.3000,  ...,  0.0245,  0.0404, -0.8259]],
       grad_fn=<AddmmBackward>)


In [ ]:
# for whole data only

## Mirna (No Cross validation)


In [ ]:
data_miRnaSeq = pd.read_csv('data_miRnaSeq.csv')
data_miRnaSeq = data_miRnaSeq.iloc[:, 1:]
npary_miRna = data_miRnaSeq.to_numpy()

#norm_miRna = normalize(array_miRnaSeq, norm = "l2")
scaler = MinMaxScaler()
scaled_miRna = scaler.fit_transform(npary_miRna)

In [ ]:
miRna_torch = torch.FloatTensor(scaled_miRna)

miRna_loader = torch.utils.data.DataLoader(
    miRna_torch, batch_size = 256, shuffle=False
)

embed_dim = scaled_miRna.shape[1]

In [ ]:
# build up ae model for mirna
class autoencoder(nn.Module):
  def __init__(self):
    super(autoencoder, self).__init__()
    self.encoder = nn.Sequential(
      nn.Linear(embed_dim, 256),
      nn.ReLU(True),
      nn.Linear(256, 128))
    self.decoder = nn.Sequential(
      nn.Linear(128, 256),
      nn.ReLU(True), 
      nn.Linear(256, embed_dim), 
      nn.Tanh())
    
  def forward(self, x):
      x = self.encoder(x)
      x = self.decoder(x)
      return x

In [ ]:
# minmax scaler mirna
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model_mirna128 = autoencoder().to(device)

criterion = nn.MSELoss()
optimizer = optim.Adam(model_mirna128.parameters(), lr=0.001)

epochs = 10
#batch_size = 256

for epoch in range(epochs):
  model_mirna128.train()
  for batch_features in miRna_loader:
    output = model_mirna128(batch_features)
    loss = criterion(output, batch_features)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

  print('epoch [{}/{}], loss:{:.4f}'
          .format(epoch + 1, epochs, loss.data.numpy()))
  

epoch [1/10], loss:0.0781
epoch [2/10], loss:0.0417
epoch [3/10], loss:0.0226
epoch [4/10], loss:0.0185
epoch [5/10], loss:0.0176
epoch [6/10], loss:0.0162
epoch [7/10], loss:0.0154
epoch [8/10], loss:0.0149
epoch [9/10], loss:0.0146
epoch [10/10], loss:0.0145


In [ ]:
model_mirna128.eval()

for features in miRna_loader:
  test = features

result_mirna128 = model_mirna128.encoder(test)

resultNp_mirna128 = result_mirna128.cpu().detach().numpy()

np.savetxt('resultNp_mirna104-128.csv', resultNp_mirna128, delimiter=',')

array([[ 0.46319434, -0.13032623, -0.03938269, ...,  0.46743885,
        -0.22245201, -0.3501378 ],
       [ 0.795352  , -0.1801069 ,  0.00738584, ...,  0.70923835,
        -0.36854056, -0.5305142 ],
       [ 0.55283695, -0.13001405, -0.02533646, ...,  0.55947953,
        -0.2599942 , -0.42309454],
       ...,
       [ 0.62339664, -0.14806284, -0.05587918, ...,  0.6592212 ,
        -0.3343306 , -0.4683654 ],
       [ 0.65795475, -0.17544797, -0.02611945, ...,  0.63121736,
        -0.30837235, -0.466317  ],
       [ 0.7439706 , -0.14961256,  0.00157071, ...,  0.7285044 ,
        -0.32549438, -0.5925204 ]], dtype=float32)

### pre process is normalizaed

In [ ]:
# normalized mirna
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = autoencoder().to(device)

criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

epochs = 10
batch_size = 256

for epoch in range(epochs):
 # loss = 0
  for batch_features in miRna_loader:
    output = model(batch_features)
    loss = criterion(output, batch_features)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

  #  loss += loss.item()
  
  #loss = loss / len(miRna_loader)

  print('epoch [{}/{}], loss:{:.4f}'
          .format(epoch + 1, epochs, loss.data.numpy()))

epoch [1/10], loss:0.0018
epoch [2/10], loss:0.0009
epoch [3/10], loss:0.0005
epoch [4/10], loss:0.0002
epoch [5/10], loss:0.0001
epoch [6/10], loss:0.0001
epoch [7/10], loss:0.0001
epoch [8/10], loss:0.0001
epoch [9/10], loss:0.0001
epoch [10/10], loss:0.0001


In [ ]:

data_methylation = pd.read_csv('data_methylation.csv')

In [ ]:

array_methylation = []



for i in range(0, ):
  temp = []
  for j in range(1, ):
    temp.append(data_methylation.iloc[i][j])
  array_methylation.append(temp)


In [ ]:



#norm_methylation = normalize(array_methylation, norm = "l2")

scaler = MinMaxScaler()

#scaled_methylation = scaler.fit_transform(array_methylation)


#print(scaled_methylation.shape)

(616, 823)


In [ ]:

# methy_torch = torch.FloatTensor(scaled_methylation)
# methy_loader = torch.utils.data.DataLoader(
#     methy_torch, batch_size = 256, shuffle=True
# )
# print(methy_loader)


# make search on the dataloader and how to handle this before put in AE model.

In [ ]:
# build up ae model for methylation
class autoencoder(nn.Module):
  def __init__(self):
    super(autoencoder, self).__init__()
    self.encoder = nn.Sequential(
      nn.Linear(823, 256),
      nn.ReLU(True),
      nn.Linear(256, 128),
      nn.ReLu(True),
      )
    self.decoder = nn.Sequential(
      nn.Linear(128, 256),
      nn.ReLU(True), 
      nn.Linear(256, 823), 
      nn.Tanh())
    
  def getLowEmbeds(self, x):
      
    
  def forward(self, x):
      x = self.encoder(x)
      
      x = self.decoder(x)
      return x

In [ ]:

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = autoencoder().to(device)

criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

epochs = 10
batch_size = 256

for epoch in range(epochs):
 # loss = 0
  for batch_features in miRna_loader:
    output = model(batch_features)
    loss = criterion(output, batch_features)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

  print('epoch [{}/{}], loss:{:.4f}'
          .format(epoch + 1, epochs, loss.data.numpy()))
  

In [ ]:
#RNAseq 
id = "1siCbnbxD3Farp2QDoSE0EkvPtq5NAnxU"
downloaded = drive.CreateFile({'id':id}) 
downloaded.GetContentFile('data_scnv128.csv')

data_scnv = pd.read_csv('data_scnv128.csv')

In [ ]:
scnv = data_scnv.iloc[:, 1:]
scnv

1q21.3    1q44      3p25.1    3q26.32   ...  0.55  0.56  0.57  0.58
0      3.6569    0.1874   -0.4576    0.2586  ...     0     0     0     0
1      0.3873    0.3858    0.4438    0.4765  ...     0     0     0     0
2      0.0833    0.4121    0.0000   -0.1448  ...     0     0     0     0
3      0.5887    0.6172   -0.0162   -0.0577  ...     0     0     0     0
4      0.0000    0.0000    0.0046   -0.0028  ...     0     0     0     0
..        ...       ...       ...       ...  ...   ...   ...   ...   ...
611    1.8555    1.8555   -0.0856   -0.0856  ...     0     0     0     0
612    0.2754    0.2754    0.0011    0.0011  ...     0     0     0     0
613    0.0122    0.0043   -0.2560   -0.2653  ...     0     0     0     0
614    0.4855    0.4964   -0.1585   -0.1585  ...     0     0     0     0
615    0.6693    0.6614   -0.0109   -0.0177  ...     0     0     0     0

[616 rows x 128 columns]

In [ ]:
scnv_npary = scnv.to_numpy()
scnv_npary

array([[3.6569, 0.1874, -0.4576, ..., 0, 0, 0],
       [0.3873, 0.3858, 0.4438, ..., 0, 0, 0],
       [0.0833, 0.4121, 0.0, ..., 0, 0, 0],
       ...,
       [0.0122, 0.0043, -0.256, ..., 0, 0, 0],
       [0.4855, 0.4964, -0.1585, ..., 0, 0, 0],
       [0.6693, 0.6614, -0.0109, ..., 0, 0, 0]], dtype=object)

In [ ]:
'Ω' in scnv_npary
string = np.where(scnv_npary == 'Ω')
print(string)
print(scnv_npary[string])

print(scnv_npary[4])
print(scnv_npary[0])

(array([0]), array([69]))
['Ω']
[0.0 0.0 0.0046 -0.0028 -0.0039 0.0338 -0.0193 -0.0102 0.0171 0.0171
 0.9728 0.0085 0.0207 0.0018 0.0018 0.0121 -0.3438 -0.0149 0.0233 0.0357
 0.105 0.289 0.289 0.289 1.127 0.2952 0.2952 0.0288 0.0 0.0 0.0429 0.0089
 0.016 -0.0057 -0.6381 0.0212 -0.0193 -0.015 -0.0102 -0.0036 -0.0036
 -0.6626 0.3251 0.3251 0.3251 0.3259 0.0207 0.0372 0.0138 0.0018 -0.652
 -0.652 -0.3438 -0.0149 -0.0149 0.0048 0.0357 0.0357 0.0072 -0.6684
 -0.6687 0.289 0.0134 -0.7006 0.2952 0.0303 -0.0135 -0.0278 0.0128 '0' 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[3.6569 0.1874 -0.4576 0.2586 3.6569 0.1659 0.147 -1.0883 0.1976 0.1976
 0.2218 -0.4827 -0.4676 0.1843 2.0965 2.6037 0.1862 3.6569 -0.4534 -0.4279
 0.1184 -0.5673 0.0783 0.0783 0.0 0.0 0.0 1.8238 0.069 0.2159 -0.3991
 -0.4659 -0.4717 -0.38 0.2476 0.2875 0.147 -1.0883 -1.119 0.2267 0.2087
 0.1829 -0.4577 -0.488 -0.488 -0.488 -0.4676 -0.4676 0.1054 -0.5

In [ ]:
scaler = MinMaxScaler()
scaled_SCNV128 = scaler.fit(scnv_npary)
scaled_SCNV128

ValueError: ignored

In [ ]:
class Encoder(nn.Module):
  def __init__(self):
    super(Encoder, self).__init__()
    self.encoder = nn.Sequential(
        nn.Linear(embed_dim, 256),
        nn.ReLU(True),
        nn.Linear(256,128)
    )

  def forward(self, x):
    output = self.encoder(x)
    return output

class Decoder(nn.Module):
  def __init__(self):
    super(Decoder, self).__init__()
    self.decoder = nn.Sequential(
        nn.Linear(128, 256),
        nn.ReLU(True),
        nn.Linear(256, embed_dim)
    )

  def forward(self, x):
    output = self.decoder(x)
    return output

class AutoEncoder(nn.Module):
  def __init__(self):
    super(AutoEncoder, self).__init__()
    self.encoder = Encoder()
    self.decoder = Decoder()

  def forward(self, x):
    x = self.encoder(x)
    output = self.decoder(x)
    return output
    